-- MySQL Script generated by MySQL Workbench
-- Tue Aug 24 00:33:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET
@OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET
@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET
@OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE
`mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USERS`;

CREATE TABLE IF NOT EXISTS `mydb`.`USERS`
(
    `USER_ID` BIGINT
(
    12
) NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR
(
    255
) NOT NULL,
    `LAST_NAME` VARCHAR
(
    255
) NOT NULL,
    `E_MAIL` VARCHAR
(
    255
) NOT NULL,
    `PASS_WORD` VARCHAR
(
    64
) NOT NULL,
    PRIMARY KEY
(
    `USER_ID`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUESTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QUESTIONS`;

CREATE TABLE IF NOT EXISTS `mydb`.`QUESTIONS`
(
    `QUESTION_ID` BIGINT
(
    12
) NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR
(
    255
) NOT NULL,
    `WORDING` VARCHAR
(
    3000
) NULL DEFAULT NULL,
    `QUESTION` VARCHAR
(
    500
) NOT NULL,
    `SUBJECT` VARCHAR
(
    45
) NOT NULL,
    `AUTHOR_ID` BIGINT
(
    12
) NOT NULL,
    `USER_ID` BIGINT
(
    12
) NOT NULL,
    PRIMARY KEY
(
    `QUESTION_ID`
),
    INDEX `fk_QUESTIONS_USERS_idx`
(
    `USER_ID` ASC
) VISIBLE,
    CONSTRAINT `fk_QUESTIONS_USERS`
    FOREIGN KEY
(
    `USER_ID`
)
    REFERENCES `mydb`.`USERS`
(
    `USER_ID`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVALUATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EVALUATION`;

CREATE TABLE IF NOT EXISTS `mydb`.`EVALUATION`
(
    `LIST_TITLE` VARCHAR
(
    255
) NOT NULL,
    `EVALUATION_ID` BIGINT
(
    12
) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY
(
    `EVALUATION_ID`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAP_QUESTIONS_EVALUATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MAP_QUESTIONS_EVALUATIONS`;

CREATE TABLE IF NOT EXISTS `mydb`.`MAP_QUESTIONS_EVALUATIONS`
(
    `USERS_USER_ID` BIGINT
(
    12
) NOT NULL,
    `EVALUATION_EVALUATION_ID` BIGINT
(
    12
) NOT NULL,
    `QUESTIONS_QUESTION_ID` BIGINT
(
    12
) NOT NULL,
    INDEX `fk_MAP_QUESTIONS_EVALUATIONS_EVALUATION1_idx`
(
    `EVALUATION_EVALUATION_ID` ASC
) VISIBLE,
    INDEX `fk_MAP_QUESTIONS_EVALUATIONS_QUESTIONS1_idx`
(
    `QUESTIONS_QUESTION_ID` ASC
) VISIBLE,
    CONSTRAINT `fk_MAP_QUESTIONS_EVALUATIONS_USERS1`
    FOREIGN KEY
(
    `USERS_USER_ID`
)
    REFERENCES `mydb`.`USERS`
(
    `USER_ID`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_MAP_QUESTIONS_EVALUATIONS_EVALUATION1`
    FOREIGN KEY
(
    `EVALUATION_EVALUATION_ID`
)
    REFERENCES `mydb`.`EVALUATION`
(
    `EVALUATION_ID`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_MAP_QUESTIONS_EVALUATIONS_QUESTIONS1`
    FOREIGN KEY
(
    `QUESTIONS_QUESTION_ID`
)
    REFERENCES `mydb`.`QUESTIONS`
(
    `QUESTION_ID`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET
SQL_MODE=@OLD_SQL_MODE;
SET
FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET
UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
